on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write
  pull-requests: write

name: auto-merge

jobs:
  auto-merge:

    runs-on: ubuntu-latest
    if: "${{ contains(github.event.pull_request.labels.*.name, 'autorelease: snapshot') }}"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PR Merge
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: gh pr merge --admin --squash ${{ github.event.pull_request.number }}